Apa itu pandas ?? 
- Library di python khusus 
  untuk data analysis & manipulation 
- Dibangun di atas Numpy 
- Dengan Pandas, maka python aka menjadi 
  seperti R

1. Import library

In [46]:
import pandas as pd
import os
from dotenv import load_dotenv

In [ ]:
insurance_dataset = pd.read_csv("../../dataset/insurance.csv")

insurance_dataset.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [48]:
insurance_dataset.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

# export dataset ke jenis file lain

Export file csv ke csv

In [ ]:
# csv to csv
path = "../../dataset/"
file_name = "data_lain.csv"
insurance_dataset.to_csv(f"{path}{file_name}", index=False)

print(f"Dataset insurace.csv berhasil di export menjadi {file_name}")
print(f"Pada path : {path + file_name}")

Dataset insurace.csv berhasil di export menjadi data_lain.csv
Pada path : ../dataset/data_lain.csv

Export csv ke excel

In [50]:
file_name = "data_excel.xlsx"
insurance_dataset.to_excel(f"{path}{file_name}", index=False)

print(f"Dataset insurace.csv berhasil di export menjadi {file_name}")
print(f"Pada path : {path + file_name}")

Dataset insurace.csv berhasil di export menjadi data_excel.xlsx
Pada path : ../dataset/data_excel.xlsx

Read Data HTML

In [51]:
load_dotenv()
url = os.getenv("FDIC_URL")
data_html_fdic = pd.read_html(url)

df_bank = data_html_fdic[0]

Export data html ke data excel

In [52]:
file_name = "data_bank.csv"
df_bank.to_csv(f"{path}{file_name}", index=False)

Export dari csv ke sql

In [53]:
from sqlalchemy import create_engine
mesin = create_engine(f'sqlite:///{path}asuransi.db')
insurance_dataset.to_sql(f'tabel_asuransi', con=mesin, index=False, if_exists='replace')
print("Data asuransi berhasil di export menjadi sql")

Data asuransi berhasil di export menjadi sql